### ISSUE TITLE
Automatic build and tests, via Travis

### ISSUE THREAD

**Issue by adriweb** [nathanfarlow/SymbolicDerivative#7]
It'd be nice to have automatic tests being run for each commits, through Travis builds.
At least it'd help detecting regressions etc.

If you don't know how to set that up, I can help you do that, it's fairly simple :)

pc/main.c could be adapted to return a string of the result expression, or at worst we could just compare binaries with the expected values, but that's a bit more work...

**Comment by nathanfarlow** [comment]
This sounds great! I will try to implement it sometime after I get back from Thanksgiving. I might poke you sometime in the future for some help ;)

**Comment by nathanfarlow** [comment]
Closed because we are implementing all this on the updated [PineappleCAS](https://github.com/nathanfarlow/PineappleCAS) and won't really be updating this code :)
