### ISSUE TITLE
Calculator Clears Ram with Equation

### ISSUE THREAD

**Issue by AlecHaring** [nathanfarlow/SymbolicDerivative#9]
After trying to run the equation cos(tan(sqr(sin(x)))*sec^2(sqr(sin(x)))*1/2sin(x)^(-1/2)*cos(x), the calculator goes black for 1/2 second and then clears the ram. I'm assuming this is due to a limit of ram and the only way the calculator solves this is by clearing the ram.
<img width="517" alt="screen shot 2018-10-24 at 8 44 47 am" src="https://user-images.githubusercontent.com/19616756/47431079-19409180-d769-11e8-9244-dc56b5ae3248.png">

**Comment by nathanfarlow** [comment]
You would be correct. Unfortunately, this program is not memory-efficient and does not check whether or not there is sufficient memory, eventually leading to a RAM reset with complicated equations. I've created a new project https://github.com/nathanfarlow/PineappleCAS that will handle these issues outlined above. As such, I won't be fixing this program and will instead implement the improvements in the currently incomplete PineappleCAS.
